# Generated by Django 4.2.13 on 2024-09-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_alter_blog_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
